# App of Apps for cluster-default-tooling
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-default-tooling
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Stig-Johnny/cluster-gitops.git'
    targetRevision: HEAD
    path: cluster-default-tooling
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# All child Applications should be defined as separate YAML files in this directory.
# Remove explicit child Application definitions from this file.
# ArgoCD will recursively discover and manage all Application manifests in this directory.
