# ArgoCD Application for NFS CSI Driver
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-csi/csi-driver-nfs.git
    targetRevision: v4.7.0
    path: deploy/helm/csi-driver-nfs
    helm:
      values: |
        controller:
          runOnControlPlane: true
        node:
          runOnControlPlane: true
        storageClass:
          create: true
          name: nfs-csi
          parameters:
            server: 100.95.36.122
            share: /volume1/docker
          reclaimPolicy: Retain
          mountOptions: []
          defaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
