---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-pat
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCFrgOuWFaCWegzk9GMb+2+sPzWASgnu8VDpkquWXdbJg26tJckUkpGw0x6pyyASITR6LX3C47uKzrXeOnl4PyAs7peG7WFYoKNFbXSjTPlKOH+wyUaezbTmJztoDP1rDyKC7epNF5dG55xMUocNceXWND6vJhYNdW7sHjHoILnCSJrMwc9E7/KXMziBKBEpvs3fwq3WA7HpCYBc7xd4ALtukFLaQNBUog5YA9wSzyV18zw9I8z9RLRpW76BSLrgAmCvWhHceMW8AsvpjVKewpyny2LTk0U85xzeLIyrl16YGWWDJ5eLIn3f1uMaC4l/jKLehRfzxw2gVG97OKqHDrBq6DifY7MAglvXPFm1LSchDGmqA8ZkI1Cs559QAxppOfoHfeT2TmnkzcOrKhkAoB6y2r3beNrWg2pXm9l5LsdPFFp5cGcqPUZn7fOEGxNr9r0X8sDVTAKa1o0iaroxPTTzFhGC2ZKL5GCk00j2aMIyHcGzspkOUDByhpZzjU5+9/5sRAJKt3acKv7bD/CodsnvTiOELzZBT3fGa+YBT+v0OWB2QDlxsLptkXxYoa/dO/z2PS8k1mrTHbHIf39GMaVlWc16Sy1HlceMrfCnpBcQpDtAYFcykxFAcBuWnhoXKchz6DEGtcKKFx+AT01DaJjmHes5ES2qKwFsKhUlrvIDVp8bLczE+MOySew3BQ9RErS3bphmtgExzDwg1EvdCxcnBhUcF7jcABxhUfbkQH05sYkZG6gTpb1
  template:
    metadata:
      creationTimestamp: null
      name: github-pat
      namespace: arc-runners
